/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author guico
 */
import connection.Database;
import controller.Sistema;
import java.util.List;
import javax.swing.JOptionPane;
import model.Tarefa;
import model.Usuario;
import java.sql.*;
import java.util.ArrayList;
import model.RelatorioTarefa;

public class MenuLider extends javax.swing.JFrame {

    private Sistema sistema;
    private Usuario usuario;

    /**
     * Creates new form MenuLider
     */
    public MenuLider(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        sistema = new Sistema();
        setSize(1440, 1024);
        setResizable(false);
        lblNome.setText(usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEquipes = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnGerenciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Oswald Medium", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bem vindo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        lblNome.setFont(new java.awt.Font("Oswald Medium", 0, 22)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 560, 30));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 360, 90));

        btnEquipes.setBorder(null);
        btnEquipes.setContentAreaFilled(false);
        btnEquipes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipes.setOpaque(false);
        btnEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 360, 90));

        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setOpaque(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 700, 360, 90));

        btnRelatorio.setBorder(null);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorio.setOpaque(false);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 360, 90));

        btnGerenciar.setBorder(null);
        btnGerenciar.setContentAreaFilled(false);
        btnGerenciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerenciar.setOpaque(false);
        btnGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 360, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/0tela LÍDER.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new TelaPerfil(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipesActionPerformed
        // TODO add your handling code here:
        new TelaEquipeLider(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEquipesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        usuario.logout();
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        try {
            int idLiderLogado = usuario.getIdUsuario(); // ou outra forma de pegar o ID do líder

            Tarefa tarefa = new Tarefa();
            List<RelatorioTarefa> relatorio = tarefa.gerarRelatorioDoLider(idLiderLogado);
            List<String> nomesEquipes = obterNomesEquipesDoLider(idLiderLogado);

            PainelRelatorioTarefas painel = new PainelRelatorioTarefas(relatorio, nomesEquipes);
            painel.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarActionPerformed
        // TODO add your handling code here:
        DialogGerenciar dialog = new DialogGerenciar(this, usuario);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnGerenciarActionPerformed

    private List<String> obterNomesEquipesDoLider(int idLider) throws SQLException {
        List<String> nomes = new ArrayList<>();

        String sql = "SELECT nome FROM equipes WHERE id_lider = ?";
        try (Connection conn = Database.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, idLider);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                nomes.add(rs.getString("nome"));
            }
        }
        return nomes;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipes;
    private javax.swing.JButton btnGerenciar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
