/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Sistema;
import model.Usuario;

/**
 *
 * @author guico
 */

public class MenuFuncionario extends javax.swing.JFrame {

    private Sistema sistema;
    private Usuario usuario;
    /**
     * Creates new form MenuFuncionario
     */
    public MenuFuncionario(Usuario usuario) {
        
        this.usuario = usuario;
        initComponents();
        sistema = new Sistema();
        setSize(1440, 1024); 
        setResizable(false);
        txtNomeLogado.setText(usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPerfil = new javax.swing.JButton();
        btnEquipes = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeLogado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setBorder(null);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setOpaque(false);
        getContentPane().add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 360, 80));

        btnEquipes.setBorder(null);
        btnEquipes.setBorderPainted(false);
        btnEquipes.setContentAreaFilled(false);
        btnEquipes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipes.setOpaque(false);
        getContentPane().add(btnEquipes, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 360, 80));

        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setOpaque(false);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 360, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bem Vindo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtNomeLogado.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtNomeLogado.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNomeLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 830, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/0tela FUNCIONARIO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipes;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtNomeLogado;
    // End of variables declaration//GEN-END:variables
}
