/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Usuario;
import controller.Sistema;
import javax.swing.JOptionPane;
import view.TelaCadastro;

/**
 *
 * @author guico
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    private Sistema sistema;

    public TelaLogin() {
        initComponents();
        sistema = new Sistema();
        setSize(1440, 1024);
        setResizable(false); // Impede redimensionamento
        setLocationRelativeTo(null); // Centraliza na tela

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnEsqueciSenha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 530, 40));

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtSenha.setBorder(null);
        txtSenha.setOpaque(false);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, 520, 40));

        btnLogin.setBorder(null);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setOpaque(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 210, 60));

        btnCadastrar.setBorder(null);
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setOpaque(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 620, 100, 20));

        btnEsqueciSenha.setBorder(null);
        btnEsqueciSenha.setContentAreaFilled(false);
        btnEsqueciSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsqueciSenha.setOpaque(false);
        btnEsqueciSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueciSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 620, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/login_crewly.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -58, -1, 1140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText();
        String senha = new String(txtSenha.getPassword());
        Usuario usuario = sistema.autenticarUsuario(email, senha);

        if (usuario != null) {
            // Login bem-sucedido
            JOptionPane.showMessageDialog(this, "Login realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            // para o futuro, quando o login for bem sucedido seguir o passo abaixo
            // new TelaPrincipal(usuario).setVisible(true);
            if (usuario.getIdTipo() == 1) { // 1 = funcionário
                new MenuFuncionario(usuario).setVisible(true);
            } else if (usuario.getIdTipo() == 2) { // 2 = líder
                new MenuLider(usuario).setVisible(true);
            }

            this.dispose();  // Fechando a tela de login
        } else {
            // Login falhou
            JOptionPane.showMessageDialog(this, "Email ou senha incorretos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.Timer timer = new javax.swing.Timer(200, e -> {
            new TelaCadastro().setVisible(true);
            dispose();
        });
        timer.setRepeats(false); // só executa uma vez
        timer.start();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private String solicitarEmailValido() {
        while (true) {
            String email = JOptionPane.showInputDialog(this, "Digite seu e-mail:");
            if (email == null || email.trim().isEmpty()) {
                return null;
            }

            String token = sistema.gerarTokenRecuperacao(email);
            if (token != null) {
                return email;
            } else {
                JOptionPane.showMessageDialog(this, "E-mail não encontrado ou erro no envio. Tente novamente.");
            }
        }
    }

    private boolean verificarToken(String email) {
        while (true) {
            String tokenInformado = JOptionPane.showInputDialog(this, "Digite o token recebido no e-mail:");
            if (tokenInformado == null) {
                return false;
            }

            if (sistema.validarToken(email, tokenInformado)) {
                sistema.removerToken(email);
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Token inválido. Tente novamente ou clique em Cancelar para sair.");
            }
        }
    }

    private String solicitarNovaSenha() {
        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).{8,}$";
        while (true) {
            String novaSenha = JOptionPane.showInputDialog(this, "Digite a nova senha:");
            if (novaSenha == null || novaSenha.trim().isEmpty()) {
                return null;
            }

            if (!novaSenha.matches(regex)) {
                JOptionPane.showMessageDialog(this,
                        "A senha deve ter no mínimo 8 caracteres, com pelo menos:\n- 1 letra minúscula\n- 1 letra maiúscula\n- 1 número\n- 1 caractere especial (@#$%^&+=!)");
            } else {
                return novaSenha;
            }
        }
    }

    private void btnEsqueciSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueciSenhaActionPerformed
        // TODO add your handling code here:
        String email = solicitarEmailValido();
        if (email == null) {
            return;
        }

        JOptionPane.showMessageDialog(this, "Um token foi enviado para seu e-mail.");

        if (!verificarToken(email)) {
            return;
        }

        String novaSenha = solicitarNovaSenha();
        if (novaSenha == null) {
            return;
        }

        boolean sucesso = sistema.redefinirSenha(email, novaSenha);
        JOptionPane.showMessageDialog(this, sucesso ? "Senha atualizada com sucesso!" : "Erro ao atualizar a senha.");
    }//GEN-LAST:event_btnEsqueciSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsqueciSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
