/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Sistema;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import model.Usuario;
import utils.ImagemUtil;

/**
 *
 * @author guico
 */
public class TelaPerfil extends javax.swing.JFrame {

    /**
     * Creates new form TelaPerfil
     */
    private Sistema sistema;
    private Usuario usuario;
    
    public TelaPerfil(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        sistema = new Sistema();
        setSize(1440, 1024); 
        setResizable(false);
        getContentPane().setLayout(new BorderLayout());
    getContentPane().add(jLabel1, BorderLayout.CENTER);

    // Carrega a imagem original para definir o tamanho da janela
    URL urlImagem = getClass().getResource("/design/TelaPerfil.jpg");
    if (urlImagem != null) {
        ImageIcon imgIcon = new ImageIcon(urlImagem);

        // Define o tamanho da janela igual ao tamanho da imagem
        int largura = imgIcon.getIconWidth();
        int altura = imgIcon.getIconHeight();

        setSize(largura, altura);
        setMinimumSize(new Dimension(largura, altura)); // opcional: impede redimensionamento menor
        setLocationRelativeTo(null); // centraliza a janela na tela

        // Ajusta a imagem inicial no JLabel, com proporção
        ImagemUtil.ajustarImagem(jLabel1, "/design/TelaPerfil.jpg");

        // Escuta redimensionamento para ajustar a imagem junto
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                ImagemUtil.ajustarImagem(jLabel1, "/design/TelaPerfil.jpg");
            }
        });
    } else {
        System.err.println("Imagem não encontrada: /design/TelaPerfil.jpg");
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/TelaPerfil.jpg"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
