package view;

import connection.Database;
import controller.Sistema;
import javax.swing.JOptionPane;
import utils.HashUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 *
 * @author guico
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    private Sistema sistema;
    
    public TelaCadastro() {
        initComponents();
        sistema = new Sistema();
        setSize(1440, 1024); 
        setResizable(false); // Impede redimensionamento
        setLocationRelativeTo(null); // Centraliza na tela
        txtSenha.setToolTipText("<html>A senha deve ter:<br>- No mínimo 8 caracteres<br>- Uma letra maiúscula<br>- Uma letra minúscula<br>- Um caractere especial</html>");
        txtEmail.setToolTipText("<html>Formato válido de e-mail:<br>- Deve conter @ e domínio<br>Ex: usuario@exemplo.com</html>");
        txtNome.setToolTipText("<html>O nome deve conter:<br>- Pelo menos 3 letras<br>- Apenas letras (sem números ou símbolos)</html>");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnTermos = new javax.swing.JButton();
        chkTermos = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtNome.setBorder(null);
        txtNome.setOpaque(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 303, 520, 50));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 393, 520, 50));

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtSenha.setBorder(null);
        txtSenha.setOpaque(false);
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 520, 45));

        txtConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        txtConfirmarSenha.setBorder(null);
        txtConfirmarSenha.setOpaque(false);
        getContentPane().add(txtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 520, 50));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.setOpaque(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 80));

        btnCadastro.setBorder(null);
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.setOpaque(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 200, 50));

        btnTermos.setBorder(null);
        btnTermos.setContentAreaFilled(false);
        btnTermos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTermos.setOpaque(false);
        btnTermos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTermosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTermos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 670, 110, 20));

        chkTermos.setBackground(new java.awt.Color(255, 255, 255));
        chkTermos.setForeground(new java.awt.Color(0, 0, 0));
        chkTermos.setText("<html>Eu aceito os <font color='blue'><u>termos e condições</u></font></html>");
        chkTermos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTermosActionPerformed(evt);
            }
        });
        getContentPane().add(chkTermos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/telas (1).png"))); // NOI18N
        jLabel1.setOpaque(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed
    private void exibirTermos() {
    JDialog termosDialog = new JDialog(this, "Termos e Condições", true); // true significa modal
    JTextArea textArea = new JTextArea();
    String termosLGPD = "Ao aceitar este termo, você concorda com o uso dos seus dados pessoais conforme a Lei Geral de Proteção de Dados (LGPD). "
            + "Os dados fornecidos serão utilizados exclusivamente para a execução deste serviço e não serão compartilhados com terceiros sem seu consentimento expresso. "
            + "Você tem o direito de acessar, corrigir ou excluir seus dados a qualquer momento. "
            + "Caso tenha dúvidas sobre o tratamento de seus dados, entre em contato conosco para mais informações.";
    textArea.setText(termosLGPD);
    textArea.setWrapStyleWord(true);
    textArea.setLineWrap(true);
    textArea.setCaretPosition(0);
    textArea.setEditable(false);

    JScrollPane scrollPane = new JScrollPane(textArea);
    termosDialog.getContentPane().add(scrollPane);

    termosDialog.setSize(400, 300);
    termosDialog.setLocationRelativeTo(this); // Centraliza o dialog em relação ao JFrame
    termosDialog.setVisible(true);
}
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        if (!chkTermos.isSelected()) {
        JOptionPane.showMessageDialog(null, "Você precisa aceitar os termos e condições para concluir o cadastro.");
        return; // Impede o cadastro de continuar
        }
        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String senha = new String(txtSenha.getPassword());
        String confirmarSenha = new String(txtConfirmarSenha.getPassword());

        // Validação do nome (letras e espaços, mínimo 3)
        if (!nome.matches("^[A-Za-zÀ-ÿ\\s]{3,}$")) {
            JOptionPane.showMessageDialog(null, "Nome inválido. Use apenas letras e pelo menos 3 caracteres.");
            return;
        }

        // Validação do e-mail
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(null, "E-mail inválido. Digite um e-mail no formato correto.");
            return;
        }

        // Validação de senha forte
        if (!senha.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).{8,}$")) {
            JOptionPane.showMessageDialog(null, "A senha deve conter ao menos 8 caracteres, uma letra maiúscula, uma minúscula, um número e um símbolo.");
            return;
        }

        // Verifica se as senhas coincidem
        if (!senha.equals(confirmarSenha)) {
            JOptionPane.showMessageDialog(null, "As senhas não coincidem.");
            return;
        }

        // Gerar hash da senha
        String senhaHash = HashUtil.gerarHash(senha);

        // cadastro no banco
        try (Connection conexao = Database.getConnection()) {
            String sql = "INSERT INTO usuarios (nome, email, senha_hash, id_tipo, consentimento_lgpd) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement stmt = conexao.prepareStatement(sql);
            stmt.setString(1, nome);
            stmt.setString(2, email);
            stmt.setString(3, senhaHash);
            stmt.setInt(4, 1); // padrão 1 para funcionario, lider sera colocado maualmente no bd com tipo 2
            stmt.setBoolean(5, true); // consentimento LGPD aceito

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + e.getMessage());
        }
        new TelaLogin().setVisible(true);
            dispose();

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.Timer timer = new javax.swing.Timer(200, e -> {
        new TelaLogin().setVisible(true);
        dispose();
        });
        timer.setRepeats(false); // só uma execução
        timer.start();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void chkTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTermosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTermosActionPerformed

    private void btnTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTermosActionPerformed
        // TODO add your handling code here:
        exibirTermos();
    }//GEN-LAST:event_btnTermosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnTermos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chkTermos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
